name: Build OrcaManga

on:
  workflow_dispatch: # تشغيل يدوي

jobs:
  build-orcamanga:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build OrcaManga extension
        run: ./gradlew :src:ar:orcamanga:assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: orcamanga-apk
          path: src/ar/orcamanga/build/outputs/**/*.apk
